name: bible
description: A simple application to interact with multiple bible APIs from a single place
version: 1.0.0
homepage: https://github.com/joshpetit/bible/

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  http: ^0.13.3
  reference_parser: ^3.0.0

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
